/*
 * Competitor API
 * Web-facing API for the challenge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.schwaben_devs.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.micronaut.core.annotation.NonNull;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.annotation.Generated;

import java.util.Objects;

/**
 * CarTypeCount
 */
@Serdeable
@JsonPropertyOrder({
    CarTypeCount.JSON_PROPERTY_SMALL,
    CarTypeCount.JSON_PROPERTY_SPORTS,
    CarTypeCount.JSON_PROPERTY_LUXURY,
    CarTypeCount.JSON_PROPERTY_FAMILY
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class CarTypeCount {

    public static final String JSON_PROPERTY_SMALL = "small";
    public static final String JSON_PROPERTY_SPORTS = "sports";
    public static final String JSON_PROPERTY_LUXURY = "luxury";
    public static final String JSON_PROPERTY_FAMILY = "family";

    /**
     * The number of offers with the car type small
     */
    @NonNull
    @JsonProperty(JSON_PROPERTY_SMALL)
    private Long small;

    /**
     * The number of offers with the car type sports
     */
    @NonNull
    @JsonProperty(JSON_PROPERTY_SPORTS)
    private Long sports;

    /**
     * The number of offers with the car type luxury
     */
    @NonNull
    @JsonProperty(JSON_PROPERTY_LUXURY)
    private Long luxury;

    /**
     * The number of offers with the car type family
     */
    @NonNull
    @JsonProperty(JSON_PROPERTY_FAMILY)
    private Long family;

    public CarTypeCount(Long small, Long sports, Long luxury, Long family) {
        this.small = small;
        this.sports = sports;
        this.luxury = luxury;
        this.family = family;
    }

    /**
     * The number of offers with the car type small
     *
     * @return the small property value
     */
    public Long getSmall() {
        return small;
    }

    /**
     * Set the small property value
     *
     * @param small property value to set
     */
    public void setSmall(Long small) {
        this.small = small;
    }

    /**
     * Set small in a chainable fashion.
     *
     * @return The same instance of CarTypeCount for chaining.
     */
    public CarTypeCount small(Long small) {
        this.small = small;
        return this;
    }

    /**
     * The number of offers with the car type sports
     *
     * @return the sports property value
     */
    public Long getSports() {
        return sports;
    }

    /**
     * Set the sports property value
     *
     * @param sports property value to set
     */
    public void setSports(Long sports) {
        this.sports = sports;
    }

    /**
     * Set sports in a chainable fashion.
     *
     * @return The same instance of CarTypeCount for chaining.
     */
    public CarTypeCount sports(Long sports) {
        this.sports = sports;
        return this;
    }

    /**
     * The number of offers with the car type luxury
     *
     * @return the luxury property value
     */
    public Long getLuxury() {
        return luxury;
    }

    /**
     * Set the luxury property value
     *
     * @param luxury property value to set
     */
    public void setLuxury(Long luxury) {
        this.luxury = luxury;
    }

    /**
     * Set luxury in a chainable fashion.
     *
     * @return The same instance of CarTypeCount for chaining.
     */
    public CarTypeCount luxury(Long luxury) {
        this.luxury = luxury;
        return this;
    }

    /**
     * The number of offers with the car type family
     *
     * @return the family property value
     */
    public Long getFamily() {
        return family;
    }

    /**
     * Set the family property value
     *
     * @param family property value to set
     */
    public void setFamily(Long family) {
        this.family = family;
    }

    /**
     * Set family in a chainable fashion.
     *
     * @return The same instance of CarTypeCount for chaining.
     */
    public CarTypeCount family(Long family) {
        this.family = family;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CarTypeCount carTypeCount = (CarTypeCount) o;
        return Objects.equals(small, carTypeCount.small) &&
            Objects.equals(sports, carTypeCount.sports) &&
            Objects.equals(luxury, carTypeCount.luxury) &&
            Objects.equals(family, carTypeCount.family);
    }

    @Override
    public int hashCode() {
        return Objects.hash(small, sports, luxury, family);
    }

    @Override
    public String toString() {
        return "CarTypeCount("
            + "small: " + getSmall() + ", "
            + "sports: " + getSports() + ", "
            + "luxury: " + getLuxury() + ", "
            + "family: " + getFamily()
            + ")";
    }

}