/*
 * Competitor API
 * Web-facing API for the challenge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.schwaben_devs.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.micronaut.core.annotation.NonNull;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.annotation.Generated;


import java.util.Objects;

/**
 * FreeKilometerRange
 */
@Serdeable
@JsonPropertyOrder({
    FreeKilometerRange.JSON_PROPERTY_START,
    FreeKilometerRange.JSON_PROPERTY_END,
    FreeKilometerRange.JSON_PROPERTY_COUNT
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class FreeKilometerRange {

    public static final String JSON_PROPERTY_START = "start";
    public static final String JSON_PROPERTY_END = "end";
    public static final String JSON_PROPERTY_COUNT = "count";

    /**
     * The start of the free kilometer range
     */
    @NonNull
    @JsonProperty(JSON_PROPERTY_START)
    private Integer start;

    /**
     * The end of the free kilometer range
     */
    @NonNull
    @JsonProperty(JSON_PROPERTY_END)
    private Integer end;

    /**
     * The number of offers in this free kilometer range
     */
    @NonNull
    @JsonProperty(JSON_PROPERTY_COUNT)
    private Long count;

    public FreeKilometerRange(Integer start, Integer end, Long count) {
        this.start = start;
        this.end = end;
        this.count = count;
    }

    /**
     * The start of the free kilometer range
     *
     * @return the start property value
     */
    public Integer getStart() {
        return start;
    }

    /**
     * Set the start property value
     *
     * @param start property value to set
     */
    public void setStart(Integer start) {
        this.start = start;
    }

    /**
     * Set start in a chainable fashion.
     *
     * @return The same instance of FreeKilometerRange for chaining.
     */
    public FreeKilometerRange start(Integer start) {
        this.start = start;
        return this;
    }

    /**
     * The end of the free kilometer range
     *
     * @return the end property value
     */
    public Integer getEnd() {
        return end;
    }

    /**
     * Set the end property value
     *
     * @param end property value to set
     */
    public void setEnd(Integer end) {
        this.end = end;
    }

    /**
     * Set end in a chainable fashion.
     *
     * @return The same instance of FreeKilometerRange for chaining.
     */
    public FreeKilometerRange end(Integer end) {
        this.end = end;
        return this;
    }

    /**
     * The number of offers in this free kilometer range
     *
     * @return the count property value
     */
    public Long getCount() {
        return count;
    }

    /**
     * Set the count property value
     *
     * @param count property value to set
     */
    public void setCount(Long count) {
        this.count = count;
    }

    /**
     * Set count in a chainable fashion.
     *
     * @return The same instance of FreeKilometerRange for chaining.
     */
    public FreeKilometerRange count(Long count) {
        this.count = count;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FreeKilometerRange freeKilometerRange = (FreeKilometerRange) o;
        return Objects.equals(start, freeKilometerRange.start) &&
            Objects.equals(end, freeKilometerRange.end) &&
            Objects.equals(count, freeKilometerRange.count);
    }

    @Override
    public int hashCode() {
        return Objects.hash(start, end, count);
    }

    @Override
    public String toString() {
        return "FreeKilometerRange("
            + "start: " + getStart() + ", "
            + "end: " + getEnd() + ", "
            + "count: " + getCount()
            + ")";
    }

}