/*
 * Competitor API
 * Web-facing API for the challenge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.schwaben_devs.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.annotation.Generated;
import jakarta.annotation.Nonnull;

import java.util.Objects;

/**
 * VollkaskoCount
 */
@Serdeable
@JsonPropertyOrder({
    VollkaskoCount.JSON_PROPERTY_TRUE_COUNT,
    VollkaskoCount.JSON_PROPERTY_FALSE_COUNT
})
@Generated("io.micronaut.openapi.generator.JavaMicronautServerCodegen")
public class VollkaskoCount {

    public static final String JSON_PROPERTY_TRUE_COUNT = "trueCount";
    public static final String JSON_PROPERTY_FALSE_COUNT = "falseCount";

    /**
     * The number of offers with vollkasko
     */
    @Nonnull
    @JsonProperty(JSON_PROPERTY_TRUE_COUNT)
    private Long trueCount;

    /**
     * The number of offers without Vollkasko
     */
    @Nonnull
    @JsonProperty(JSON_PROPERTY_FALSE_COUNT)
    private Long falseCount;

    public VollkaskoCount(Long trueCount, Long falseCount) {
        this.trueCount = trueCount;
        this.falseCount = falseCount;
    }

    /**
     * The number of offers with vollkasko
     *
     * @return the trueCount property value
     */
    public Long getTrueCount() {
        return trueCount;
    }

    /**
     * Set the trueCount property value
     *
     * @param trueCount property value to set
     */
    public void setTrueCount(Long trueCount) {
        this.trueCount = trueCount;
    }

    /**
     * Set trueCount in a chainable fashion.
     *
     * @return The same instance of VollkaskoCount for chaining.
     */
    public VollkaskoCount trueCount(Long trueCount) {
        this.trueCount = trueCount;
        return this;
    }

    /**
     * The number of offers without Vollkasko
     *
     * @return the falseCount property value
     */
    public Long getFalseCount() {
        return falseCount;
    }

    /**
     * Set the falseCount property value
     *
     * @param falseCount property value to set
     */
    public void setFalseCount(Long falseCount) {
        this.falseCount = falseCount;
    }

    /**
     * Set falseCount in a chainable fashion.
     *
     * @return The same instance of VollkaskoCount for chaining.
     */
    public VollkaskoCount falseCount(Long falseCount) {
        this.falseCount = falseCount;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VollkaskoCount vollkaskoCount = (VollkaskoCount) o;
        return Objects.equals(trueCount, vollkaskoCount.trueCount) &&
            Objects.equals(falseCount, vollkaskoCount.falseCount);
    }

    @Override
    public int hashCode() {
        return Objects.hash(trueCount, falseCount);
    }

    @Override
    public String toString() {
        return "VollkaskoCount("
            + "trueCount: " + getTrueCount() + ", "
            + "falseCount: " + getFalseCount()
            + ")";
    }

}